export const categoriesData = [
  {
    id: 1,
    title: "School",
    subtitle: "(Classes 1-10)",
    stats: "12 Subjects / Special Programs",
    imageUrl: "https://picsum.photos/seed/cat-school/400/260",
    imageHint: "school students studying",
    href: "/mentors?category=school",
    theme: "yellow",
    buttonClass: "bg-blue-500 hover:bg-blue-600",
    borderClass: "border-yellow-300",
    titleClass: "bg-yellow-100 dark:bg-yellow-900/30",
  },
  {
    id: 2,
    title: "Intermediate",
    subtitle: "(11-12)",
    stats: "7 Subjects, Entrance Exams",
    imageUrl: "https://picsum.photos/seed/cat-inter/400/260",
    imageHint: "teenagers studying books",
    href: "/mentors?category=intermediate",
    theme: "sky",
    buttonClass: "bg-cyan-500 hover:bg-cyan-600",
    borderClass: "border-sky-300",
    titleClass: "bg-sky-100 dark:bg-sky-900/30",
  },
  {
    id: 3,
    title: "BTech / College / Skills",
    subtitle: "",
    stats: "15 Topics",
    imageUrl: "https://picsum.photos/seed/cat-btech/400/260",
    imageHint: "college students programming",
    href: "/mentors?category=btech",
    theme: "blue",
    buttonClass: "bg-indigo-500 hover:bg-indigo-600",
    borderClass: "border-blue-300",
    titleClass: "bg-blue-100 dark:bg-blue-900/30",
  },
  {
    id: 4,
    title: "Law Mentoring",
    subtitle: "",
    stats: "5 Topics, 5 Exam Coaching",
    imageUrl: "https://picsum.photos/seed/cat-law/400/260",
    imageHint: "law books and gavel",
    href: "/mentors?category=law",
    theme: "emerald",
    buttonClass: "bg-emerald-600 hover:bg-emerald-700",
    borderClass: "border-emerald-300",
    titleClass: "bg-emerald-100 dark:bg-emerald-900/30",
  },
  {
    id: 5,
    title: "Government Exams",
    subtitle: "",
    stats: "7 Exams / Subjects",
    imageUrl: "https://picsum.photos/seed/cat-govt/400/260",
    imageHint: "government building facade",
    href: "/mentors?category=govt",
    theme: "lime",
    buttonClass: "bg-green-600 hover:bg-green-700",
    borderClass: "border-lime-300",
    titleClass: "bg-lime-100 dark:bg-lime-900/30",
  },
];
