export const mentors = [
  {
    id: 1,
    name: 'Sarah Johnson',
    imageUrl: 'https://picsum.photos/seed/m1/300/300',
    imageHint: 'professional woman',
    expertise: ['JEE Mains', 'Physics', 'Advanced Math'],
    rating: 4.9,
    reviews: 125,
    price: 50,
  },
  {
    id: 2,
    name: 'David Chen',
    imageUrl: 'https://picsum.photos/seed/m2/300/300',
    imageHint: 'professional man',
    expertise: ['NEET', 'Biology', 'Chemistry'],
    rating: 4.8,
    reviews: 98,
    price: 45,
  },
  {
    id: 3,
    name: 'Priya Patel',
    imageUrl: 'https://picsum.photos/seed/m3/300/300',
    imageHint: 'professional woman',
    expertise: ['UPSC', 'Public Admin', 'History'],
    rating: 4.9,
    reviews: 210,
    price: 60,
  },
  {
    id: 4,
    name: 'Michael Rodriguez',
    imageUrl: 'https://picsum.photos/seed/m4/300/300',
    imageHint: 'professional man',
    expertise: ['Web Development', 'React', 'Node.js'],
    rating: 4.7,
    reviews: 75,
    price: 55,
  },
  {
    id: 5,
    name: 'Emily Williams',
    imageUrl: `https://picsum.photos/seed/m5/300/300`,
    imageHint: 'professional woman',
    expertise: ['CLAT', 'Constitutional Law', 'Logic'],
    rating: 4.8,
    reviews: 82,
    price: 50,
  },
  {
    id: 6,
    name: 'James Brown',
    imageUrl: `https://picsum.photos/seed/m6/300/300`,
    imageHint: 'professional man',
    expertise: ['SSC CGL', 'Quantitative Aptitude'],
    rating: 4.6,
    reviews: 65,
    price: 40,
  },
  {
    id: 7,
    name: 'Jessica Lee',
    imageUrl: `https://picsum.photos/seed/m7/300/300`,
    imageHint: 'professional person',
    expertise: ['IELTS', 'Spoken English', 'Grammar'],
    rating: 4.9,
    reviews: 150,
    price: 48,
  },
  {
    id: 8,
    name: 'Chris Taylor',
    imageUrl: `https://picsum.photos/seed/m8/300/300`,
    imageHint: 'professional portrait',
    expertise: ['Data Science', 'Python', 'Machine Learning'],
    rating: 4.8,
    reviews: 110,
    price: 65,
  },
];
